[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Set the Node.js version if needed, e.g.,
  # NODE_VERSION = "18"
  # NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
